### ISSUE TITLE
Allow private setXXX methods

### ISSUE THREAD

**Issue by gorkaio** [ulabox/ulabox-coding-standard#1]
Currently function name validator does not allow private methods with names starting with 'set'. However, there are legit uses for private setters, ie: those that encapsulate field validations:

``` php
public function __construct($name) {
    $this->setName($name);
}

public function rename($newName)
{
    $this->setName($newName);
}

private function setName($name)
{
    Assert::string($name);
    Assert::notBlank(trim($name));
    $this->name = $name;
}
```

We should change function name validator to allow 'setXXX' methods as long as they are private.

**Comment by acasademont** [comment]
don't see the point, why the private method? all the code in the private
method could be in the rename public method and call the rename public
method from the constructor, no?

**Comment by gorkaio** [comment]
If you think about it in an event oriented approach, setting the name on object creation and renaming the object are two very different actions, but they both need to validate the name and set its value. In a more 'semantic' way, you are not "renaming" the object on instantiation, you are just setting its name for the first time.

The following example might show what I mean:

``` php
public function __construct(ObjectId $id, $name) {
    $this->id = $id;
    $this->setName($name);
    $this->record(new ObjectWasCreated($id, $name));
}

public function rename($newName)
{
    $this->setName($newName);
    $this->record(new ObjectWasRenamed($this->id, $newName));
}

private function setName($name)
{
    Assert::string($name);
    Assert::notBlank(trim($name));
    $this->name = $name;
}
```

**Comment by acasademont** [comment]
:+1: go for it!

**Comment by acasademont** [comment]
shit, sorry, wrong button!

**Comment by gorkaio** [comment]
Merged
